name: CI

on:
  pull_request:
  push:
      branches:
      - main

jobs:
  mix_test:
    name: Test Elixir ${{matrix.version}}
    runs-on: ubuntu-latest
    container: elixir:${{ matrix.version }}-alpine
    strategy:
      matrix:
        include:
          - version: "1.11"
          - version: "1.10"
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/_build
            ~/deps
            ~/assets/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: mix deps.get
        env:
          MIX_ENV: test
        run: |
          apk add build-base git
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: mix ecto.create && ecto.migrate
        env:
          MIX_ENV: test
        run: |
          mix ecto.create
          mix ecto.migrate
      - name: mix test
        run: mix test
