name: CI

on:
  pull_request:
  push:
      branches:
      - main

jobs:
  mix_test:
    name: Test Elixir ${{ matrix.version }}
    runs-on: ubuntu-latest
    container: elixir:${{ matrix.version }}-alpine
    strategy:
      matrix:
        include:
          - version: "1.11"
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      DB_URL: postgres://postgres:postgres@postgres/keila
    steps:
      - name: install system packages
        run: apk add build-base git tar
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            _build
            deps
            assets/node_modules
          key: keila-${{ runner.os }}-elixir-${{ matrix.version }}-${{ hashFiles('mix.lock') }}
      - name: mix deps.get
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: mix ecto.create && ecto.migrate
        run: |
          mix ecto.create
          mix ecto.migrate
      - name: mix test
        run: mix test
